# Encoding the Chategorical data

In [43]:
import pandas as pd
import numpy as np

In [44]:
df=pd.read_csv('customer.csv')

In [45]:
df.sample(5)

,age,gender,review,education,purchased
20,57,Female,Average,School,Yes
14,15,Male,Poor,PG,Yes
29,83,Female,Average,UG,Yes
16,59,Male,Poor,UG,Yes
9,74,Male,Good,UG,Yes


In [46]:
df=df.iloc[:,2:4]

In [59]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split( df.iloc[:,0:2],df.iloc[:,-1],test_size=0.2)

In [60]:
x_train.head()

,review,education
12,Poor,School
43,Poor,PG
11,Good,UG
33,Good,PG
3,Good,PG


# Ordinal Encoding

In [61]:
from sklearn.preprocessing import OrdinalEncoder
oe=OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [62]:
oe.fit(x_train)

,categories,"[['Poor', 'Average', ...], ['School', 'UG', ...]]"
,dtype,<class 'numpy.float64'>
,handle_unknown,'error'
,unknown_value,None
,encoded_missing_value,nan
,min_frequency,None
,max_categories,None


In [63]:
x_train=oe.transform(x_train)

In [64]:
x_train

array([[0., 0.],
       [0., 2.],
       [2., 1.],
       [2., 2.],
       [2., 2.],
       [2., 1.],
       [0., 1.],
       [0., 1.],
       [2., 2.],
       [0., 0.],
       [0., 0.],
       [2., 1.],
       [0., 2.],
       [0., 0.],
       [0., 2.],
       [1., 0.],
       [2., 2.],
       [0., 2.],
       [2., 0.],
       [0., 0.],
       [2., 1.],
       [0., 2.],
       [2., 0.],
       [1., 0.],
       [1., 1.],
       [1., 1.],
       [0., 2.],
       [1., 1.],
       [2., 2.],
       [1., 0.],
       [2., 0.],
       [1., 1.],
       [1., 0.],
       [2., 1.],
       [1., 2.],
       [0., 2.],
       [0., 1.],
       [0., 2.],
       [0., 2.],
       [1., 2.]])

# Lebel Encoding

In [65]:
from sklearn.preprocessing import LabelEncoder

In [66]:
le=LabelEncoder()

In [67]:
le.fit(y_train)

LabelEncoder()

In [68]:
y_train=le.transform(y_train)
y_test=le.transform(y_test)

In [69]:
y_train

array([1, 0, 2, 0, 0, 2, 2, 2, 0, 1, 1, 2, 0, 1, 0, 1, 0, 0, 1, 1, 2, 0,
       1, 1, 2, 2, 0, 2, 0, 1, 1, 2, 1, 2, 0, 0, 2, 0, 0, 0])

# One-Hot Encoding

In [88]:
df=pd.read_csv('cars.csv')

In [89]:
df.head()

,brand,km_driven,fuel,owner,selling_price
0,Maruti,145500,Diesel,First Owner,450000
1,Skoda,120000,Diesel,Second Owner,370000
2,Honda,140000,Petrol,Third Owner,158000
3,Hyundai,127000,Diesel,First Owner,225000
4,Maruti,120000,Petrol,First Owner,130000


In [98]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split( df.iloc[:,0:4],df.iloc[:,-1],test_size=0.2)

In [99]:
x_train.head()

,brand,km_driven,fuel,owner
2295,Maruti,3000,Petrol,First Owner
183,Hyundai,44000,Petrol,Second Owner
8079,Tata,129000,Diesel,Third Owner
5275,Hyundai,70000,Diesel,Second Owner
1185,Toyota,80000,Diesel,First Owner


In [100]:
from sklearn.preprocessing import OneHotEncoder

In [107]:
ohe=OneHotEncoder(drop='first',sparse_output=False,dtype=np.int64)

In [108]:
x_train_new = ohe.fit_transform(x_train[['fuel','owner']])

In [109]:
x_test_new=ohe.transform(x_test[['fuel','owner']])

In [110]:
x_train_new.shape

(6502, 7)

In [111]:
x_train_new

array([[0, 0, 1, ..., 0, 0, 0],
       [0, 0, 1, ..., 1, 0, 0],
       [1, 0, 0, ..., 0, 0, 1],
       ...,
       [0, 0, 1, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0]], shape=(6502, 7))

In [112]:
np.hstack((x_train[['brand','km_driven']].values,x_train_new))

array([['Maruti', 3000, 0, ..., 0, 0, 0],
       ['Hyundai', 44000, 0, ..., 1, 0, 0],
       ['Tata', 129000, 1, ..., 0, 0, 1],
       ...,
       ['Maruti', 22000, 0, ..., 0, 0, 0],
       ['Toyota', 250000, 1, ..., 0, 0, 0],
       ['Ford', 15000, 0, ..., 0, 0, 0]], shape=(6502, 9), dtype=object)